import requests

#########################################################################################################################
# user_id:  written as HACKATHONUSER*** from 100 to 299 (101 doesn't seem to work for some reason?)


def get_user_accounts(user_id):
    url = "http://ncrdev-dev.apigee.net/digitalbanking/db-accounts/v1/accounts?hostUserId=" + \
        str(user_id)

    payload = {}
    # need to remember to consistently update this
    headers = {
        'Authorization': 'Bearer D3SwtlumsU8iFC8PK8ao3pD3TLlH',
        'transactionId': 'c625c9aa-fc9f-473a-bd19-9f0870bcb134',
        'Accept': 'application/json'
    }

    response = requests.request("GET", url, headers=headers, data=payload)
    return response.text.encode('utf8')
#########################################################################################################################

#########################################################################################################################


def get_user_account(account_id, user_id):
    url = "http://ncrdev-dev.apigee.net/digitalbanking/db-accounts/v1/accounts/" + \
        str(account_id) + "?hostUserId=" + str(user_id)
    payload = {}
    headers = {
        'Authorization': 'Bearer D3SwtlumsU8iFC8PK8ao3pD3TLlH',
        'transactionId': 'fdd1542a-bcfd-439b-a6a1-5a064023b0ce',
        'Accept': 'application/json'
    }

    response = requests.request("GET", url, headers=headers, data=payload)
    return response.text.encode('utf8')
#########################################################################################################################

#########################################################################################################################
# account_id is the first value in each entry in the list of accounts generated by get_user_accounts


def get_transactions_from_account(account_id, user_id):
    url = "http://ncrdev-dev.apigee.net/digitalbanking/db-transactions/v1/transactions?accountId=" + \
        str(account_id) + "&hostUserId=" + str(user_id)
    payload = {}
    headers = {
        'Authorization': 'Bearer D3SwtlumsU8iFC8PK8ao3pD3TLlH',
        'transactionId': 'fdd1542a-bcfd-439b-a6a1-5a064023b0ce',
        'Accept': 'application/json'
    }

    response = requests.request("GET", url, headers=headers, data=payload)
    return response.text.encode('utf8')


print(get_user_accounts("HACKATHONUSER250"))
print("\n\n\n\n\n\n")
print(get_user_account("RvHQVyPWntXOE0FurfM7vbj7MOfvn3iTFHrvIfv94bs", "HACKATHONUSER250"))
print("\n\n\n\n\n\n")
print(get_transactions_from_account("RvHQVyPWntXOE0FurfM7vbj7MOfvn3iTFHrvIfv94bs", "HACKATHONUSER250"))